name: PR Checks

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # PHP / Laravel setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, sqlite
          coverage: none

      - name: Install PHP dependencies
        run: |
          cd api
          composer install --no-progress --prefer-dist --optimize-autoloader

      # Node / Vue setup
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM dependencies
        run: |
          cd frontend
          npm ci || npm install

      # Dummy Laravel test (placeholder)
      - name: Laravel Version Test
        run: |
          cd api
          php artisan --version

      # Dummy Vue build check
      - name: Build Vue
        run: |
          cd frontend
          npm run build || echo "No frontend yet"

      # Spell check
      - name: Spell Check
        uses: streetsidesoftware/cspell-action@v2
        with:
          files: "**/*.{php,vue,js,md}"

      # Lint PHP
      - name: Install PHP_CodeSniffer
        run: |
          composer global require "squizlabs/php_codesniffer=*"

      - name: PHP Lint
        run: |
          ~/.composer/vendor/bin/phpcs --standard=PSR12 api/app/ api/routes/ || echo "No PHP lint errors"

      # Lint Vue / JS
      - name: Install ESLint
        run: |
          cd frontend
          npm install eslint || echo "No ESLint installed"

      - name: Vue Lint
        run: |
          cd frontend
          npm run lint || echo "No Vue lint errors"
