name: PR Checks

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, sqlite
          coverage: none

      - name: Install PHP dependencies
        run: |
          cd api
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Laravel Build (Cache Config & Routes)
        run: |
          cd api
          php artisan config:cache
          php artisan route:cache || echo "No routes to cache"

      - name: Run PHPUnit tests
        run: |
          cd api
          cp .env.example .env
          php artisan key:generate
          php artisan migrate --env=testing --database=sqlite --force || echo "No migrations"
          ./vendor/bin/phpunit

      - name: Spell Check
        uses: streetsidesoftware/cspell-action@v2
        with:
          files: "**/*.{php,md}"

      - name: Install PHP_CodeSniffer
        run: |
          composer global require "squizlabs/php_codesniffer=*"

      - name: PHP Lint
        run: |
          ~/.composer/vendor/bin/phpcs --standard=PSR12 api/app/ api/routes/ || echo "No PHP lint errors"
