name: PR Checks

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ------------------------
      # 📦 BACKEND (Laravel)
      # ------------------------

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, sqlite
          coverage: none

      - name: Install Composer dependencies
        run: cd api && composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Dummy Laravel Test
        run: cd api && php artisan --version

      - name: Spell Check (PHP)
        uses: streetsidesoftware/cspell-action@v2
        with:
          files: |
            api/app/**/*.php
            api/routes/**/*.php

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: PHP Lint
        run: cd api && ~/.composer/vendor/bin/phpcs --standard=PSR12 app/ routes/ || echo "No PHP lint errors"

      # ------------------------
      # 🖼️ FRONTEND (Vue 3)
      # ------------------------

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Build frontend
        run: cd frontend && npm run build

      - name: Lint frontend
        run: cd frontend && npm run lint || echo "No lint errors"

      - name: Install Spanish Dictionary
        run: npm install -g @cspell/dict-es-es

      - name: Spell Check Frontend
        uses: streetsidesoftware/cspell-action@v2
        with:
          config: frontend/cspell.json
          files: |
            frontend/src/**/*.js
            frontend/src/**/*.vue
            frontend/src/**/*.json
      
