name: PR Checks

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # PHP / Laravel setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, sqlite
          coverage: none

      - name: Install Composer dependencies
        run: cd api && composer install --no-progress --prefer-dist --optimize-autoloader

      # Dummy Laravel tests
      - name: Dummy Laravel Test
        run: cd api && php artisan --version

      # Spell check
      - name: Spell Check
        uses: streetsidesoftware/cspell-action@v2
        with:
          files: |
            api/app/**/*.php
            api/routes/**/*.php
            api/README.md

      # Lint PHP (requires phpcs)
      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: PHP Lint
        run: cd api && ~/.composer/vendor/bin/phpcs --standard=PSR12 app/ routes/ || echo "No PHP lint errors"
